apiVersion: v1
data:
  mapRoles: |
    -rolearn: arn:aws:iam::019537562652:role/CodeBuildKubectlRole
    username: CodeBuildKubectlRole
    groups:
      -system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"-rolearn: arn:aws:iam::019537562652:role/CodeBuildKubectlRole\nusername: CodeBuildKubectlRole\ngroups:\n  -system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2024-01-16T18:04:10Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2021177"
  uid: d8963fb5-bcc2-4b2e-92f7-a186dc819152
